server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: backend-estudiantes-service
          uri: lb://backend-estudiantes-service
          predicates:
            - Path=/estudiante/**
        - id: backend-cuotas-service
          uri: lb://backend-cuotas-service
          predicates:
            - Path=/cuotas/**
        - id: backend-examenes-service
          uri: lb://backend-examenes-service
          predicates:
            - Path=/examen/**